[package]
name = "iitpp-roblox/localaudio"
repository = "https://github.com/IITPP-Roblox/LocalAudio"
description = "Module for playing audios on demand as data instead of instances."
license = "MIT"
authors = ["IITPP-Roblox"]
version = "1.5.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]